apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: "TCP"
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-api
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: "TCP"
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: "TCP"
  type: LoadBalancer
